---
title: "Merge_pre&post_DDMT"
output: html_document
---


```{r load libraries}
library(pacman)
pacman::p_load(dplyr, tidyr, lubridate, ggplot2)
options(digits.secs = 3)

```

#load preDDMT
``` {r}
PreDDMT <- read.csv("E:/Myotis_vivesi/17_49/Mviv17_49_ACC_Call.csv")

str(PreDDMT)

names(PreDDMT)[2] <- "Event"
names(PreDDMT)
```

#load postDDMT
``` {r}
PostDDMT1 <- read.csv("E:/Myotis_vivesi/DDMT/Mviv17_49_ACC_Call_split1.csv", sep = ";")
PostDDMT2 <- read.csv("E:/Myotis_vivesi/DDMT/Mviv17_49_ACC_Call_split2.csv", sep = ";")
PostDDMT3 <- read.csv("E:/Myotis_vivesi/DDMT/Mviv17_49_ACC_Call_split3.csv", sep = ";")


str(PostDDMT1)
names(PostDDMT1)[1] <- "Event"
names(PostDDMT1)[3] <- "Time"
names(PostDDMT1)

names(PostDDMT2)[1] <- "Event"
names(PostDDMT2)[3] <- "Time"

names(PostDDMT3)[1] <- "Event"
names(PostDDMT3)[3] <- "Time"

# merge postDDMT splits for Mviv17_49

PostDDMT <- rbind(PostDDMT1, PostDDMT2, PostDDMT3)
PostDDMT <- PostDDMT[order(PostDDMT$Event), ]
PostDDMT <- PostDDMT %>% distinct(Event, .keep_all = TRUE)
```

#merge pre and postDDMT
``` {r}
names(PreDDMT)
names(PostDDMT)
ALL_DDMT <- merge(PreDDMT, PostDDMT, by.x = "Event", by.y = "Event")
names(ALL_DDMT)
ALL_DDMT_clean <- ALL_DDMT[-c(2:12)]
names(ALL_DDMT_clean)

names(ALL_DDMT_clean)[8] <- "ACCX"
names(ALL_DDMT_clean)[9] <- "ACCY"
names(ALL_DDMT_clean)[10] <- "ACCZ"
names(ALL_DDMT_clean)[11] <- "stACCX"
names(ALL_DDMT_clean)[12] <- "stACCY"
names(ALL_DDMT_clean)[13] <- "stACCZ"
names(ALL_DDMT_clean)[14] <- "dACCX"
names(ALL_DDMT_clean)[15] <- "dACCY"
names(ALL_DDMT_clean)[16] <- "dACCZ"
names(ALL_DDMT_clean)[19] <- "Pitch"
names(ALL_DDMT_clean)[20] <- "Roll"
```

#save and check Metrics
``` {r}
write.csv(ALL_DDMT_clean, file = "E:/Myotis_vivesi/17_49/Mviv17_49_metrics.csv", row.names = FALSE)

Metrics <- read.csv("E:/Myotis_vivesi/17_49/Mviv17_49_metrics.csv")
str(Metrics)
```