---
title: "Mviv17_60_cleanup"
output: html_document
---

#load packages
```{r}
library(pacman)
p_load(lubridate, tidyverse, dplyr, timetools, data.table)
op <- options(digits.secs = 3)

list.files(path = "E:/Myotis_vivesi/17_60")
```

#cleanup true_buzz: end times of buzzes taken from audio files
```{r}
true_buzz <- fread("E:/Myotis_vivesi/17_60/Mviv17_60_truebuzz_offset.csv")

#rename columns in true_buzz_offset
names(true_buzz)
names(true_buzz)[1] <- "file"
names(true_buzz)[2] <- "offset"
names(true_buzz)[3] <- "loud_buzz_end"
names(true_buzz)[4] <- "start_clip"
names(true_buzz)[5] <- "segment"
names(true_buzz)

#rearrange by startclip and segment
true_buzz$start_clip <- ymd_hms(true_buzz$start_clip)
true_buzz <- true_buzz %>% arrange(start_clip, segment)

#calculate end of buzz in each clip
true_buzz$buzz_end <- NA
true_buzz$buzz_end <- true_buzz$start_clip + true_buzz$offset

write.csv(true_buzz, "E:/Myotis_vivesi/17_60/Mviv17_60_true_buzz_end.csv", row.names = FALSE)

```

#clean up metrics: output of DDMT; acc with some metrics
```{r}
metrics <- fread("E:/Myotis_vivesi/17_60/Mviv17_60_metrics.csv")

str(metrics)

```

#clean up buzz_acc: summarized acc(metrics) by buzz audio index with behaviour label (half second acc)
```{r}
buzz_acc <- fread("E:/Myotis_vivesi/17_60/Mviv17_60_buzz_acc.csv")

str(buzz_acc)

```