---
title: "Random Forest"
output: html_document
editor_options: 
  chunk_output_type: console
---

# load libraries

```{r}
library(pacman)
p_load(lubridate, tidyverse, dplyr, timetools, data.table)
op <- options(digits.secs = 3)
```

# create training(dev) and test(val) data set

```{r}
#### compare active (buzz, search, comm) vs inactive (roost)
data <- read.csv("E:/Myotis_vivesi/17_34_rm1/Mviv17_34_acc_behav.csv")
names(data)
data <- data[, c(66, 1:65)]

data <- na.omit(data)

table(data$behav)

data$behav[data$behav == "buzz"] <- "comm"
data$behav[data$behav == "search"] <- "comm"
data$behav[data$behav == "comm"] <- "active"
data$behav[data$behav == "roost"] <- "inactive"

table(data$behav)

write.csv(data, file = "E:/Myotis_vivesi/17_34_rm1/active_inactive/Mviv17_34_active_inactive.csv", row.names = FALSE)
####


data <- read.csv("E:/Myotis_vivesi/17_34_rm1/active_inactive/Mviv17_34_active_inactive.csv")


data$behav <- as.factor(data$behav)

# Development, Validation
sample.ind <- sample(2, nrow(data), replace = T, prob = c(0.6, 0.4))
dev <- data[which(sample.ind == 1),] # development sample, 60% 
val <- data[which(sample.ind == 2),] # validation sample, 40%

# check same distributions
table(dev$behav) / nrow(dev)
table(val$behav) / nrow(val)

# check for behaviours to exclude
table(dev$behav)
table(val$behav)
```

# train RF

```{r}
# Random Forest
library(randomForest)

# load Rdata
load(file = "E:/Myotis_vivesi/17_34_rm1/active_inactive/RF_ai.Rdata")

dev <- dev[,-67]
val <- val[,-67]

set.seed(222)
R.Forest <- randomForest(formula = behav ~ ., data = dev, ntree = 30, mtry = 8, importance = TRUE)
# we want to predict "behav" (response variable) using each of the remaining columns of data (predictor variables)

```

# tune parameters ntree and mtry

# tune ntree

```{r}
# First set mtry to default (sqrt of total number of all predictors) and search for the optimal ntree value
# To find best ntree, build RF with different ntree values (100, 200, 300….,1,000). We build 10 RF classifiers for each ntree value, record the OOB error rate and select ntree value with minimum OOB error

R.Forest

# number of trees that minimizes OOB
error.rate <- as.data.frame(R.Forest$err.rate)
error.rate$ntree <- row.names(error.rate)
(min.OOB <- error.rate[which.min(error.rate$OOB),])


# OOB rates for different ntree and corresponding best ntree value:
# 50  =  0.11% -> 22 (OOB = 0.001126972)
# 100 =  0.11% -> 22 (OOB = 0.001126972)
# 200 =  0.11% -> 22 (OOB = 0.001126972)
# 300 =  0.11% -> 22 (OOB = 0.001126972)

# --> best ntree = 22 (OOB = 0.001126972)


CM.dev <- R.Forest$confusion


# Check error rates for each behaviour
colnames(error.rate)

# Create a plot before running the lines
plot(error.rate$ntree, error.rate[,1], type = "l", ylim = c(0,0.005), ylab = "Error rate", xlab = "Number of trees")

# Part1
lines(error.rate[,2], col = 1)   #black -> active
lines(error.rate[,3], col = 2)   #red   -> inactive
lines(error.rate[,1], col = 3)   #green -> OOB

abline(v = 22, col = "darkgreen")

legend(19.35, 0.0052, c("active","inactive", "OOB", "min.OOB"), lty = rep(1,8), lwd = rep(1,8), col = c(1:3, "darkgreen"))

```

# tune mtry

```{r}
# apply similar procedure such that random forest is run 10 times. The optimal number of predictors selected for split is selected for which out of bag error rate stabilizes and reach minimum

R.Forest
# OOB rates for different mtry:
# 2   = 0.15%
# 3   = 0.15%
# 4   = 0.17%
# 5   = 0.11%
# 6   = 0.11%
# 7   = 0.15%
# 8   = 0.11% (default)
# 9   = 0.15%
# 10  = 0.23%

# -> best mtry = 8

```

# Variable Importance

```{r}
# 700 x 500
varImpPlot(R.Forest, sort = TRUE, main = "Variable Importance ai", n.var = 20)

# Variables ordered in a list
GINI <- data.frame(importance(R.Forest, type = 2, scale = F))
GINI$Variables <- row.names(GINI)
GINI <- GINI[order(GINI$MeanDecreaseGini, decreasing = TRUE),]
GINI <- GINI[1:20,]

# 650 x 400
barplot(GINI$MeanDecreaseGini, names.arg = GINI$Variables, las = 2, bty = "L", ylab = "Mean Gini Decrease ai")


GINI <- data.frame(importance(R.Forest, type = 2, scale = F))
GINI$Variables <- row.names(GINI)
GINI <- GINI[order(GINI$MeanDecreaseGini, decreasing = FALSE),]
GINI <- GINI[45:65,]

# 400 x 500
dotchart(GINI$MeanDecreaseGini, labels = GINI$Variables, main = "Mean Gini Decrease ai")


var.Accuracy <- data.frame(importance(R.Forest, type = 1, scale = T))
var.Accuracy$Variables <- row.names(var.Accuracy)
var.Accuracy <- var.Accuracy[order(var.Accuracy$MeanDecreaseAccuracy, decreasing = TRUE),]
var.Accuracy <- var.Accuracy[1:20,]

# 650 x 400
barplot(var.Accuracy$MeanDecreaseAccuracy, names.arg = var.Accuracy$Variables, las = 2, bty = "L", ylab = "Mean Accuracy Decrease ai")


var.Accuracy <- data.frame(importance(R.Forest, type = 1, scale = T))
var.Accuracy$Variables <- row.names(var.Accuracy)
var.Accuracy <- var.Accuracy[order(var.Accuracy$MeanDecreaseAccuracy, decreasing = FALSE),]
var.Accuracy <- var.Accuracy[45:65,]

# 400 x 500
dotchart(var.Accuracy$MeanDecreaseAccuracy, labels =  var.Accuracy$Variables, main = "Mean Accuracy Decrease ai")

```

# validate how good the model is on the test data (val)

```{r}

dev$pred <- predict(R.Forest, dev)
val$pred <- predict(R.Forest, val)

CM.samp = table(val$pred, val$behav) # same as CM.val??


CM.val = matrix(data = 0, nrow = ncol(CM.samp), ncol = ncol(CM.samp), dimnames = list(colnames(CM.samp), colnames(CM.samp)))

for (j in 1:nrow(CM.samp)){
  CM.val[(rownames(CM.samp[j,,drop = F])),] = CM.samp[j,]
}   



Recall = diag(CM.val) / apply(CM.val, 2, sum)
Precision = diag(CM.val) / apply(CM.val, 1, sum)
Accuracy = sum(diag(CM.val)) / sum(CM.val)


# 650 x 400
names(Recall) = c("active", "inactive")
plot(Recall ~ Precision, pch = 16, bty = "L", las = 1, ylim = c(0,1), xlim = c(0.5, 1), cex = 1, main = "active vs inactive")
text(Precision, Recall, names(Recall), pos = 2, cex = 0.9)


save(dev, val, R.Forest, CM.dev, error.rate, min.OOB, var.Accuracy, GINI, CM.val, Precision, Recall, Accuracy, file = "E:/Myotis_vivesi/17_34_rm1/active_inactive/RF_ai.Rdata")




load(file = "E:/Myotis_vivesi/17_34_rm1/active_inactive/RF_ai.Rdata")


# column =  observation, row = model prediction
CM.rel <- table(val$pred, val$behav) / nrow(val)

observations <- table(val$behav)
predictions <- table(val$pred)

options(digits = 4)
Precision <- Precision * 100
Recall <- Recall * 100


CM.val <- rbind(CM.val, observations)
CM.val <- cbind(CM.val, predictions)
CM.val <- rbind(CM.val, Precision)
CM.val <- rbind(CM.val, Recall)


write.csv(CM.val, file = "E:/Myotis_vivesi/17_34_rm1/active_inactive/CM_val.csv")



# plot CM with corresponding precision, recall, accuracy
library(kableExtra)

CM.large <- read.csv(file = "E:/Myotis_vivesi/17_34_rm1/active_inactive/CM_val.csv", sep = ";")

CM.large[(is.na(CM.large))] <- ""

names(CM.large)[1] <- "In/Out"

CM.large[1:3,]

CM.large[1:3,] %>%
  kbl(caption = "Confusion matrix: observations (columns) x predictions (rows)") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  column_spec(1, bold = T) %>%
  row_spec(0, bold = T)



## frequency distribution of most important variables

load(file = "E:/Myotis_vivesi/17_34_rm1/active_inactive/RF_ai.Rdata")

boxplot(dev$behav, dev$sd.dZ, ylab = "sd.dZ", names = levels(dev$behav), col = c(2:3))

plot(dev$behav, dev$sd.dZ, ylab = "sd.dZ", xlab = "", col = c(2:3))

hist(dev$sd.dZ, xlim = c(0, 2), xlab = "sd.dZ", main = "inactive vs. active")


hist(dev$sd.dZ[which(dev$behav == "inactive")], xlim = c(0, 1.5), xlab = "sd.dZ", main = "inactive vs active", col = "yellow")

hist(dev$sd.dZ[which(dev$behav == "active")], xlim = c(0, 1.5), xlab = "sd.dZ", col = "green", add = TRUE)



##### plot frequency distribution

library(pacman)

p_load(ggplot2, hrbrthemes, dplyr, tidyr, viridis)

mytheme <- theme(
                  plot.title = element_text(face = "bold", family = "Helvetica", size = (15), hjust = 0.5), 
                  legend.title = element_text(face = "bold", family = "Helvetica"), 
                  legend.text = element_text(family = "Helvetica"), 
                  axis.title = element_text(face = "bold", family = "Helvetica", size = (12)),
                  axis.text = element_text(family = "Helvetica", size = (10)),
                  axis.line = element_line(size = 1, colour = "black"),
                  panel.background = element_rect(fill = "white")
                  )
                  
# 650 x 400
ggplot(data = dev, aes(x = sd.dZ, group = behav, fill = behav)) +
   geom_density(adjust = 1.5, alpha = .4) +
   xlab("sd.dZ") +
   ylab("frequency") +
   ggtitle("active vs inactive") +
   labs(fill = "behaviour") +
   mytheme

####


getwd()
setwd("E:/Myotis_vivesi/17_34_rm1/active_inactive")

data <- read.csv("E:/Myotis_vivesi/17_34_rm1/active_inactive/Mviv17_34_active_inactive.csv")

load(file = "E:/Myotis_vivesi/17_34_rm1/active_inactive/RF_ai.Rdata")


library(dunn.test)
# Kruskal for diff. in median, supports histograms
kruskal.test(dev$sd.dZ ~ as.factor(dev$behav))
kruskal.active_inactive <- capture.output(print(kruskal.test(dev$sd.dZ ~ as.factor(dev$behav))))
writeLines(kruskal.active_inactive, con = "Kruskal_active_inactive.txt")

# Dunn for correction of sev. tests
dunn.test(dev$sd.dZ, g = as.factor(dev$behav), method = "bonferroni")
dunn.active_inactive <- capture.output(print(dunn.test(dev$sd.dZ, g = as.factor(dev$behav), method = "bonferroni")))
writeLines(dunn.active_inactive, con = "Dunn_active_inactive.txt")


# Plot dunn test
pdf("Significance_plot.pdf")

data_active <- data[which(data$behav == "active"), ]
data_active$behav <- as.factor(data_active$behav)

par(bty = "l", mar = c(5,5,5,2))
boxplot(data_active$sd.dZ ~ data_active$behav, ylim = c(0,1.9), ylab = "sd.dZ", xlab = "active")
lines(c(2,3), c(1.5,1.5))
lines(c(1,3), c(1.8,1.8))
#locator() #search,then esc
text(x = 2.501641, y = 1.619257, "*", cex = 1.7)
text(x = 1.920028, y = 1.920028, "*", cex = 1.7)
dev.off()

```
